In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3] , dtype= 'int32')
print(a)

[1 2 3]


In [4]:
#for dimensions we can use 
a.ndim

1

In [6]:
b = np.array([[1,2,3,4], [1.2,2.3,2.7,6.8]])
print(b)
b.ndim

[[1.  2.  3.  4. ]
 [1.2 2.3 2.7 6.8]]


2

In [7]:
b.shape

(2, 4)

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [11]:
a.itemsize

8

In [13]:
a.dtype

dtype('int64')

In [15]:
#for total size 
a.nbytes

24

In [16]:
q = np.array([[1,2,3,4,5,6,7], [2,3,6,8,3,5,3]])
print(q)

[[1 2 3 4 5 6 7]
 [2 3 6 8 3 5 3]]


In [19]:
q[1,4]

3

In [21]:
#get a specific row
q[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#get a specific column
q[: , 0]

array([1, 2])

In [23]:
#[startindex : endindex : stepsize]
#you can also change the value in the specific array of the numpy
q[1,5] = 20
print(q)

[[ 1  2  3  4  5  6  7]
 [ 2  3  6  8  3 20  3]]


In [24]:
#np.zeros((r,c)) used for 0 indexing
# for ones we can use np.ones((r,c))
#for full we can use np.full((r,c) , number , dtype = 'float32')
#for identity matrix we can use np.identity(c)
#np.matmul(a,b) for a matrix multiply rather than element wise , like with normal a*b
#for determinant we can use np.linalg.det(c)
#c = np.identity(3)


In [ ]:
#to lead a data from a file , we have to 
# filedata = np.genfromtxt('file name' , delimiter = ',')
#for much advance things on file we can do is  / are :
# filedata >50
